export const Surface = require('core/Surface');
export const Image = require('core/Image');
export React, { Component } from 'react';
export { render } from 'react-dom';
// export * from 'core/Image';
// export * from 'components/sprite';
// export * from 'components/layer';
// export * from 'components/text';
// export * from 'components/scene';
// export * from 'components/fgimage';
// export * from 'components/container';
