export * from 'core/Surface';
export * from 'core/Image';
export * from 'core/Text';
export * from 'core/Container';
export * from 'core/Layer';
export * from 'core/Scene';
export * from 'core/Textwindow';
export * from 'core/BGImage';
export * from 'core/FGImage';
export React, { Component } from 'react';
export { render } from 'react-dom';
// export * from 'core/Image';
// export * from 'components/sprite';
// export * from 'components/layer';
// export * from 'components/text';
// export * from 'components/scene';
// export * from 'components/fgimage';
// export * from 'components/container';
