export * from 'components/Surface';
export * from 'components/Image';
export * from 'components/Text';
export * from 'components/Container';
export * from 'components/Layer';
export * from 'components/Scene';
export * from 'components/Textwindow';
export * from 'components/BGImage';
export * from 'components/FGImage';
export * from 'components/Transition';
export { load as loadResource } from 'classes/Preloader';
export React, { Component } from 'react';
export { render } from 'react-dom';
// export * from 'core/Image';
// export * from 'components/sprite';
// export * from 'components/layer';
// export * from 'components/text';
// export * from 'components/scene';
// export * from 'components/fgimage';
// export * from 'components/container';
